version: '3.8'
services:
  bitebalancebackend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
      labels:
        - bitebalancebackend
      args:
        - stage=${STAGE:-none}
    environment:
      - PORT=${PORT}
      - APPLICATION_ID=${APPLICATION_ID}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_OP_USER=${POSTGRES_OP_USER}
      - POSTGRES_OP_PASSWORD=${POSTGRES_OP_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./app:/app
      - ./uploads:/tmp/uploads
    entrypoint: "./entrypoint.sh"
    command: "dev"
    ports:
      - "${{ secrets.PORT }}:${{ secrets.PORT }}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      - TZ=America/New_York
    ports:
      - 5432:5432

volumes:
  postgres_data:
